name: Suite de tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test_suite:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Copie de la liste de sources APT Ubuntu 'noble'
        run: sudo cp .github/apt_sources_list/ubuntu-noble.list /etc/apt/sources.list.d/

      - name: Installation des dépendances de SherlockFS
        run: sudo bash dependencies.sh --with-tests

      - name: Lancement de la suite de tests (`make check`)
        run: make -j check
