name: Suite de tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test_suite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Téléchargement de l'outil Criterion
        run: sudo wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 -O /tmp/criterion.tar.bz2

      - name: Création du dossier d'extraction pour l'archive de Criterion
        run: sudo mkdir -p /tmp/criterion
        
      - name: Extraction de l'archive Criterion
        run: sudo tar -xjf /tmp/criterion.tar.bz2 -C /tmp/criterion

      - name: Installation de Criterion depuis l'archive
        run: sudo cp -r /tmp/criterion/criterion-v2.3.3/share/* /usr/local/share &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/local/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/include/* /usr/local/include

      - name: Lancement de la suite de tests (`make check`)
        run: make check
