name: Test suite

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Downloading criterion package
        run: sudo wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 -O /tmp/criterion.tar.bz2

      - name: Initializing tmp directory
        run: sudo mkdir -p /tmp/criterion
        
      - name: Extracting criterion package
        run: sudo tar -xjf /tmp/criterion.tar.bz2 -C /tmp/criterion

      - name: Installing criterion package
        run: sudo cp -r /tmp/criterion/criterion-v2.3.3/share/* /usr/local/share &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/local/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/include/* /usr/local/include

      - name: Updating apt cache
        run: sudo apt-get update

      - name: Installing openssl (including headers)
        run: curl -sL https://github.com/openssl/openssl/archive/refs/heads/master.zip -o /tmp/openssl.zip &&
          sudo unzip /tmp/openssl.zip -d /tmp/openssl &&
          cd /tmp/openssl/openssl-master &&
          sudo ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl &&
          sudo make &&
          sudo make install &&
          sudo cp -r /usr/local/ssl/include/openssl /usr/local/include

      - name: Checking version of openssl
        run: openssl version

      - name: Running `make check`
        run: make check
