name: Test Suite

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check_formatting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Install `clang-format`
        run: |
          sudo apt update
          sudo apt install clang-format -y
      - name: Check source file formatting with `clang-format`
        run: |
          bash ./.github/scripts/check_formatting.sh

  test_suite:
    runs-on: ubuntu-22.04
    needs: [check_formatting]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Copy APT sources list for Ubuntu 'noble'
        run: sudo cp .github/apt_sources_list/ubuntu-noble.list /etc/apt/sources.list.d/

      - name: Install SherlockFS dependencies
        run: sudo bash dependencies.sh --with-tests

      - name: Run the test suite (`make check`)
        run: make -j check
