name: Test suite

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Downloading criterion package
        run: sudo wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 -O /tmp/criterion.tar.bz2

      - name: Initializing tmp directory
        run: sudo mkdir -p /tmp/criterion
        
      - name: Extracting criterion package
        run: sudo tar -xjf /tmp/criterion.tar.bz2 -C /tmp/criterion

      - name: Installing criterion package
        run: sudo cp -r /tmp/criterion/criterion-v2.3.3/share/* /usr/local/share &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/local/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/lib/* /usr/lib &&
          sudo cp -r /tmp/criterion/criterion-v2.3.3/include/* /usr/local/include

      - name: Adding latest APT source list
        run: echo "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list

      - name: Downloading openssl and libssl-dev from sources
        run: wget http://fr.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_3.0.2-0ubuntu1.6_i386.deb -O /tmp/libssl-dev.deb &&
          wget http://fr.archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_3.0.2-0ubuntu1.6_i386.deb -O /tmp/openssl.deb

      - name: Installing openssl and libssl-dev from sources
        run: sudo dpkg -i /tmp/libssl-dev.deb &&
          sudo dpkg -i /tmp/openssl.deb

      - name: Checking version of openssl
        run: openssl version

      - name: Running `make check`
        run: make check
